### PR TITLE
add Op("&") for nested blocks

### PR DESCRIPTION
**Pull request by R32**
hss:

```css
a {
	color: #000;
	&:hover{
		color:#fff;
		&:before{
			color:#000;
		}
		.add{
			color:#000;
		}
	}

	&.tit{
		color:#000;
	}

	.normal{
		color:#fff;
		&.join{
			color: #000;
		}
	}
}

&.hover{
	color: #f00;
}
```

output:

```css
a {
	color : #000;
}
a:hover {
	color : #fff;
}
a:hover:before {
	color : #000;
}
a:hover .add {
	color : #000;
}
a.tit {
	color : #000;
}
a .normal {
	color : #fff;
}
a .normal.join {
	color : #000;
}
.hover {
	color : #f00;
}
```

### CODE REVIEW

**Comment by ncannasse** [comment]
Thanks!
Could you change `| OpDefault | OpJoint -> if cs.operator == OpJoint then "" else " "` by `| OpDefault -> " " | OpJoint -> ""` ?

**Comment by R32** [comment]
like this?

```ocaml
IO.write ch (match c.operator {
	| OpDefault -> " "
	| OpJoint -> ""
	| OpChild -> ">"
```
i have no deal, but the `c.operator` and `cs.operator` are not same node

```ocaml
IO.write ch (match c.operator {
	| OpDefault | OpJoint -> if cs.operator == OpJoint then "" else " "
	| OpChild -> ">"
```

**Comment by ncannasse** [comment]
ah, I think you're right. I would need to check it but I rarely run HSS these days. I guess you tested the original change, please revert and let me merge

**Comment by R32** [comment]
reverted

**Pull request merged**
